version: '3.8'
services:
  neon-db:
    image: postgres:15
    container_name: neon-postgres
    restart: always
    environment:
      POSTGRES_USER: neon
      POSTGRES_PASSWORD: neonpassword
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - neon_data:/var/lib/postgresql/data

volumes:
  neon_data:
